### ISSUE TITLE
local variable called by cy_worker_thread_enqueue

### ISSUE THREAD

**Issue by richardlc68** [Infineon/wifi-connection-manager#1]
**Prerequisites**

Can you reproduce the problem reliably?
yes

Did you check current release notes for known issues?
yes

If this is not the latest release, have you checked newer releases? 

**Description**:

There are few places in the cy_wcm.c in \COMPONENT_LWIP which call cy_worker_thread_enqueue() to add callback and local variable as parameter, the local variable (cy_wcm_event_t) will soon be invalid after take out by cy_rtos_get_queue for dispatcher from cy_worker_thread_func() in cy_worker_thread.c. this issue will lead unexpected value of cy_wcm_event_t.

**Steps to Reproduce:**

1. 
add register after success of cy_wcm_init(): 
cy_wcm_register_event_callback(my_call_back_func);

we won't get proper event value such as CY_WCM_EVENT_CONNECTED, etc.

**Expected Result:**

we should get all valid belong to cy_wcm_event_t event value such as CY_WCM_EVENT_CONNECTED, etc.

**Actual Result:**

we won't get CY_WCM_EVENT_CONNECTED, instead, it give us invalid value which is out of range cy_wcm_event_t.

**Frequency (1/1, 1/50, 1/100):**

1/1

**Build/Commit:**

commit c7c2a0127c0d61f0c53947aad19ea9700fb6bbdb [c7c2a01]

**Target:**

STM32H7 with ThreadX+Lwip

**Compiler:**

IAR 8.50

My fix:
where call  cy_worker_thread_enqueue() with non-NULL parameter of *arg, make this local variable as staic, example in
function internal_scan_callback() change
  uint32_t scan_status;  ---->   static uint32_t scan_status;

**Comment by krshnarajd** [comment]
@richardlc68 : Looks like this has been addressed.
