### ISSUE TITLE
Code snippet example wrong assertions

### ISSUE THREAD

**Issue by jaenrig-ifx** [Infineon/wifi-connection-manager#2]
**Description**:

All WCM API return assertion of code snippet 9 (in the docs) are wrong:
https://github.com/Infineon/wifi-connection-manager/blob/master/docs/api_reference_manual/html/index.html#L946-L1218
```
  if (result == CY_RSLT_SUCCESS)
  {
      ...
      return;
  }
```
should be
```
  if (result != CY_RSLT_SUCCESS)
  {
      ...
      return;
  }
```

**Comment by krshnarajd** [comment]
@jaenrig-ifx : This is corrected in the latest release.
